// <auto-generated />
using System;
using ATMScoreBoard.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATMScoreBoard.Shared.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATMScoreBoard.Shared.DTOs.EstadisticaEquipoColRanking", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("JugadorA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JugadorB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PosicionRanking")
                        .HasColumnType("bigint");

                    b.Property<int>("PuntosRanking")
                        .HasColumnType("int");

                    b.ToTable("RankingEquipos");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.DTOs.EstadisticaJugadorRanking", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PosicionRanking")
                        .HasColumnType("bigint");

                    b.Property<int>("PuntosRanking")
                        .HasColumnType("int");

                    b.ToTable("RankingJugadores");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.Configuracion", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Clave");

                    b.ToTable("Configuraciones");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsIndividual")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.EquipoJugador", b =>
                {
                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.HasKey("EquipoId", "JugadorId");

                    b.HasIndex("JugadorId");

                    b.ToTable("EquipoJugadores");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoAId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoBId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoGanadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueVictoriaImpecable")
                        .HasColumnType("bit");

                    b.Property<int>("TipoJuego")
                        .HasColumnType("int");

                    b.Property<int>("TipoJuegoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoAId");

                    b.HasIndex("EquipoBId");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.PartidaActual", b =>
                {
                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.Property<string>("BandaEquipoA")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EquipoAId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoBId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoLisasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoJuegoId")
                        .HasColumnType("int");

                    b.HasKey("MesaId");

                    b.HasIndex("EquipoAId");

                    b.HasIndex("EquipoBId");

                    b.ToTable("PartidasActuales");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.PartidaActualBolas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroBola")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PartidasActualesBolas");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.PuntosHistoricoView", b =>
                {
                    b.Property<int>("Dias")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<long>("Orden")
                        .HasColumnType("bigint");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<int>("RivalId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("PuntosHistorico", (string)null);
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.EquipoJugador", b =>
                {
                    b.HasOne("ATMScoreBoard.Shared.Models.Equipo", "Equipo")
                        .WithMany("EquipoJugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATMScoreBoard.Shared.Models.Jugador", "Jugador")
                        .WithMany("EquipoJugadores")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.Partida", b =>
                {
                    b.HasOne("ATMScoreBoard.Shared.Models.Equipo", "EquipoA")
                        .WithMany()
                        .HasForeignKey("EquipoAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATMScoreBoard.Shared.Models.Equipo", "EquipoB")
                        .WithMany()
                        .HasForeignKey("EquipoBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipoA");

                    b.Navigation("EquipoB");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.PartidaActual", b =>
                {
                    b.HasOne("ATMScoreBoard.Shared.Models.Equipo", "EquipoA")
                        .WithMany()
                        .HasForeignKey("EquipoAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATMScoreBoard.Shared.Models.Equipo", "EquipoB")
                        .WithMany()
                        .HasForeignKey("EquipoBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipoA");

                    b.Navigation("EquipoB");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.Equipo", b =>
                {
                    b.Navigation("EquipoJugadores");
                });

            modelBuilder.Entity("ATMScoreBoard.Shared.Models.Jugador", b =>
                {
                    b.Navigation("EquipoJugadores");
                });
#pragma warning restore 612, 618
        }
    }
}
